version: '3.8'

services:
  fastapi:
    restart: always
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/src:/app
    command: ["python", "main.py"]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./certificates:/etc/nginx/certs
    depends_on:
      - fastapi
